title: Seth N Redmond, PhD
description: Genomic epidemiology, disease surveillance, and decision-grade real-world evidence
theme: jekyll-theme-slate
author: Seth Redmond
url: "https://sethnr.github.io"
github_username: sethnr
